package report

import (
	"html/template"
	"os"

	"github.com/ilightthings/shareblair/lib/smbprotocol"
)

func GenerateReport(s *smbprotocol.Target) error {
	const MainTemplate = `
	<!DOCTYPE html>
<html>
<style>
table, th, td {
  border:1px solid black;
}
</style>
<body>
	<h1>{{.HostDestination}}</h1>
	<h2>Generated by Shareblair</h2>
	<table>
	<tr>
	<th>Shares<th>
	</tr>

	{{range .ListOfShares}}
	<tr><td>\\{{$.HostDestination}}\{{.ShareName}}
	<ol>
	{{range .ListOfFiles}}
	<li id="{{.Path}}">📄 {{.Name}}</li>
	{{end}}
	{{range .ListOfFolders}}
	 <li id="{{.Path}}">📁 {{.Name}}</li>
	{{end}}
	</ol>
	{{end}}
	</tr>
	</td>
	</table>
	</body>
	`

	t, err := template.New("doc").Parse(MainTemplate)
	if err != nil {
		return err
	}

	t.Execute(os.Stdout, s)
	return nil

}
