package report

import (
	"html/template"
	"os"

	"github.com/ilightthings/shareblair/lib/smbprotocol"
)

func GenerateReport(s *smbprotocol.Target) error {
	const MainTemplate = `<h1>{{.HostDestination}}</h1>
	<h2>Generated by Shareblair</h2>
	<ul> {{range .ListOfShares}}
	`

	t, err := template.New("doc").Parse(MainTemplate)
	if err != nil {
		return err
	}

	t.Execute(os.Stdout, s)
	return nil

}
